wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.11.2
    start_time: 1679921374.538869
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.11.2
      5: 0.14.0
      8:
      - 5
feature_extractor:
  desc: null
  value: null
head:
  desc: null
  value: null
lr:
  desc: null
  value: 0.001
