repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^metrics/
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=50000"]
  - repo: local
    hooks:
      - id: black
        name: black
        args: ["--line-length", "120"]
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        language_version: python3.11
        require_serial: true
        types_or: [python, pyi]

      - id: blacken-docs
        name: blacken-docs
        description: Run `black` on python code blocks in documentation files
        entry: blacken-docs
        language: python
        language_version: python3.11
        files: '\.(rst|md|markdown|py|tex)$'

      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3.11
        types_or: [cython, pyi, python]
        args: ["--profile", "black", "--filter-files"]

      # - id: pylint
      #   name: pylint
      #   entry: pylint
      #   language: python
      #   types: [python]
      #   require_serial: true

      # - id: mypy
      #   name: mypy
      #   entry: mypy
      #   language: python
      #   types_or: [python, pyi]
      #   args: ["--ignore-missing-imports", "--scripts-are-modules"]
      #   require_serial: true
      #   additional_dependencies: []
