defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

run:
  dir: ${paths.log_dir}/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}

sweep:
  dir: ${paths.log_dir}/${hydra.job.name}
  subdir: ${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
