defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
