wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.11.2
    start_time: 1681403969.129661
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.2
      5: 0.14.0
      8:
      - 1
      - 5
