model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val/loss
  dirpath: ${hydra:run.dir}/models
  filename: best_{epoch}_{step}
  mode: min
  save_last: True
  save_top_k: 1
