# @package _global_

defaults:
  - _self_
  # - callbacks: default.yaml
  - datamodule: mnist.yaml
  - feature_extractor: deep_cnn.yaml
  - head: multiclass_linear.yaml
  - transforms: default.yaml
  - callbacks: default.yaml
  - hydra: default.yaml
  - logger: wandb.yaml
  - model: multiclass_image_classifier.yaml
  - paths: default.yaml
  - trainer: default.yaml
  - experiment: null
  - debug: null

project_name: image_classification
run_name: auto
seed: 42
