# @package _global_

trainer:
  max_epochs: 1
  limit_train_batches: 1
  limit_val_batches: 1
  limit_test_batches: 1
  detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor

run_name: debug
